create table public.users(
	user_id int not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1247483647 CACHE 1),
	user_name varchar(50) not null,
	surname varchar(50) not null,
	email varchar(50) unique not null,
	user_password varchar(50) not null,
	phone_number varchar(11) unique not null,
	image_url varchar(500) not null,
	primary key(user_id)
);

create table public.auctions(
	auction_id int not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1247483647 CACHE 1),
	auction_name varchar(50) not null,
	description text not null,
	starting_date timestamp not null,
	starting_price int not null,
	user_id int not null,
	category_id int not null,
	primary key(auction_id)
);

create table public.bids(
	bid_id int not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1247483647 CACHE 1),
	bid_value int not null,
	user_id int not null,
	auction_id int not null,
	primary key(bid_id)
);

create table public.categories(
	category_id int not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1247483647 CACHE 1),
	category_name varchar(50) not null,
	description text,
	primary key(category_id)
);

create table public.user_ratings(
	rater_user_id int not null,
	rated_user_id int not null,
	value int not null,
	primary key(rated_user_id,rater_user_id)
);

create table public.auction_images(
	auction_id int not null,
	auction_images_id int not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1247483647 CACHE 1),
	image_url text,
	primary key(auction_images_id,auction_id)
);

create table public.favorite_users(
	user_id int not null,
	favorited_user_id int not null,
	is_favorite_user boolean not null,
	primary key(user_id,favorited_user_id)
);

create table public.favorite_auctions(
	user_id int not null,
	auction_id int not null,
	is_favorite_auction boolean not null,
	primary key(user_id,auction_id)
);

alter table user_ratings
	add constraint fk_rater_user foreign key(rater_user_id) references users(user_id),
	add constraint fk_rated_user foreign key(rated_user_id) references users(user_id);

alter table favorite_users
	add constraint fk_fav_users_users foreign key(user_id) references users(user_id),
	add constraint fk_fav_users_fav_users foreign key(favorited_user_id) references users(user_id);
	
alter table bids
	add constraint fk_bids_users foreign key(user_id) references users(user_id),
	add constraint fk_bids_auctions foreign key(auction_id) references auctions(auction_id);
	
alter table auctions
	add constraint fk_auctions_categories foreign key(category_id) references categories(category_id),
	add constraint fk_auctions_users foreign key(user_id) references users(user_id);

alter table auction_images
	add constraint fk_auction_images_auctions foreign key(auction_id) references auctions(auction_id);

alter table favorite_auctions
	add constraint fk_fav_auctions_users foreign key(user_id) references users(user_id),
	add constraint fk_fav_auctions_auctions foreign key(auction_id) references auctions(auction_id);
	



